apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagestorebackend
  namespace: imagestore 
spec:
  replicas: 3
  selector:                    
    matchLabels:
      app: imagestorebackend 
  template:
    metadata:
      labels:
        app: imagestorebackend 
    spec:                      
      containers:
       - name: imagestorebackend           
         image: kaifpersonal.azurecr.io/imagestorebackend:latest  
         ports:
          - containerPort: 8007
         envFrom:
           secretRef:
             name: backend-secret 
           